### ISSUE TITLE
Using string name of interface instead of atom produces different result

### ISSUE THREAD

**Issue by electricshaman** [nerves-project/nerves_network#29]
While testing #28, I noticed that when providing the interface name as a string to `Nerves.Network.setup` that the subsequent call to `Nerves.Network.Udhcpc.renew(Process.whereis(Nerves.Udhcpc))` would not result in a lease renewal.  However, using the atom form `:usb0` did produce the expected results.

```
Nerves:           0.7.2
Nerves Bootstrap: 0.6.1
Elixir:           1.5.0
Nerves Network:   0.3.3
```

### Steps to reproduce (rpi0)

1. Setup internet connection sharing on the OSX cdc composite gadget device.
2. Connect via serial.
3. `Nerves.Network.setup :usb0, ipv4_address_method: :dhcp`
4. `Nerves.Network.Udhcpc.renew(Process.whereis(Nerves.Udhcpc))`
(observe IP address change)
5. Restart device.
6. Connect via serial.
7. `Nerves.Network.setup "usb0", ipv4_address_method: :dhcp`
8. `Nerves.Network.Udhcpc.renew(Process.whereis(Nerves.Udhcpc))`
(observe lack of IP address change)

### Expected result

Features provided by Nerves.Network should function the same regardless of whether the interface name is provided to `Nerves.Network.setup` as an atom or a string.  If the code internally expects the interface name to be an atom, then we should convert the string version to an atom before doing anything else with it.

**Comment by fhunleth** [comment]
It was never my intention for atomized interface names to work. @ConnorRigby - when you get to spec-ifying the API here, I think that you should force string names. @electricshaman - the reason that this worked is that it created a whole new GenServer to handle the `:usb0` interface rather than modify it. The modification part is the place that has the bug.

**Comment by ConnorRigby** [comment]
On setup, ill catch it if its an atom and change it over to a string. That way you can supply either and it will figure it out

**Comment by fhunleth** [comment]
I'm on the fence on automatic conversion since I'm worried about the atom forms permeating code in people's projects and then becoming confusing when people handle notifications from the SystemRegistry and see strings. Seems better to force one way that's consistent.

Also, if we add predictable interface naming to Nerves at some point, the atom-ized forms will look really inappropriate. Imagine atoms like `: enx78e7d1ea46da`

**Comment by electricshaman** [comment]
@ConnorRigby That sounds good.  I like that better than the other way around (converting string to atom).

**Comment by ConnorRigby** [comment]
#32 I added a warning message, and am converting to a string right now for `scan/1` (and `setup/2`. In the future we can drop support for atoms entirely i think.

**Comment by ConnorRigby** [comment]
All setup calls now get casted to a string. 
see [here](https://github.com/nerves-project/nerves_network/issues/41#issuecomment-370915628) for details
